// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/simple.dart';
import 'models/users_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 968616095730477910),
    name: 'SimpleEntity',
    lastPropertyId: const obx_int.IdUid(2, 7817682895597280540),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 592610845456637505),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7817682895597280540),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4795594706832066082),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(7, 8959637974532326950),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2961720697055928698),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 250252666794557336),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3405178536199817302),
        name: 'hashedPassword',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2953845309359560927),
        name: 'salt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8612518464701081865),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3698712322181984103),
        name: 'lastLogin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8959637974532326950),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4795594706832066082),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SimpleEntity: obx_int.EntityDefinition<SimpleEntity>(
      model: _entities[0],
      toOneRelations: (SimpleEntity object) => [],
      toManyRelations: (SimpleEntity object) => {},
      getId: (SimpleEntity object) => object.id,
      setId: (SimpleEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SimpleEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = SimpleEntity(id: idParam, name: nameParam);

        return object;
      },
    ),
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[1],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {},
      getId: (UserEntity object) => object.id,
      setId: (UserEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        final hashedPasswordOffset = fbb.writeString(object.hashedPassword);
        final saltOffset = fbb.writeString(object.salt);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, usernameOffset);
        fbb.addOffset(2, hashedPasswordOffset);
        fbb.addOffset(3, saltOffset);
        fbb.addInt64(4, object.createdAt);
        fbb.addInt64(5, object.lastLogin);
        fbb.addBool(6, object.isActive);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final hashedPasswordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final saltParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final lastLoginParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = UserEntity(
          id: idParam,
          username: usernameParam,
          hashedPassword: hashedPasswordParam,
          salt: saltParam,
          createdAt: createdAtParam,
          lastLogin: lastLoginParam,
          isActive: isActiveParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SimpleEntity] entity fields to define ObjectBox queries.
class SimpleEntity_ {
  /// See [SimpleEntity.id].
  static final id = obx.QueryIntegerProperty<SimpleEntity>(
    _entities[0].properties[0],
  );

  /// See [SimpleEntity.name].
  static final name = obx.QueryStringProperty<SimpleEntity>(
    _entities[0].properties[1],
  );
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.id].
  static final id = obx.QueryIntegerProperty<UserEntity>(
    _entities[1].properties[0],
  );

  /// See [UserEntity.username].
  static final username = obx.QueryStringProperty<UserEntity>(
    _entities[1].properties[1],
  );

  /// See [UserEntity.hashedPassword].
  static final hashedPassword = obx.QueryStringProperty<UserEntity>(
    _entities[1].properties[2],
  );

  /// See [UserEntity.salt].
  static final salt = obx.QueryStringProperty<UserEntity>(
    _entities[1].properties[3],
  );

  /// See [UserEntity.createdAt].
  static final createdAt = obx.QueryIntegerProperty<UserEntity>(
    _entities[1].properties[4],
  );

  /// See [UserEntity.lastLogin].
  static final lastLogin = obx.QueryIntegerProperty<UserEntity>(
    _entities[1].properties[5],
  );

  /// See [UserEntity.isActive].
  static final isActive = obx.QueryBooleanProperty<UserEntity>(
    _entities[1].properties[6],
  );
}
